import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

const orderDetailPage = read('pages/order/order-detail.vue')
const orderListPage = read('pages/order/order_list.vue')
const prescriptionDetailPage = read('pages/prescription/detail.vue')

assert.match(orderDetailPage, /redeemVouchers/)
assert.match(orderDetailPage, /therapy-voucher-card/)
assert.match(orderDetailPage, /verifyQrBase64/)
assert.match(orderDetailPage, /normalizeQrImageSrc/)
assert.match(orderDetailPage, /:src="normalizeQrImageSrc\(voucher\.verifyQrBase64\)"/)
assert.match(orderDetailPage, /formatRedeemStatus/)
assert.match(orderDetailPage, /buildRedeemVouchers/)
assert.match(orderDetailPage, /resolvePrescriptionNavigationParams/)
assert.match(orderDetailPage, /orderId=/)
assert.doesNotMatch(orderDetailPage, /:src="voucher\.verifyQrBase64"/)
assert.match(orderDetailPage, /resolvePrescriptionNavigationParams/)
assert.doesNotMatch(orderDetailPage, /prescriptionNo=\$\{this\.order\.prescriptionId\}/)
assert.doesNotMatch(orderDetailPage, /statusText:\s*['"]鍔犺浇涓璡.\.\.['"]/)

assert.match(orderListPage, /ORDER_LIST_PREVIEW_LIMIT/)
assert.match(orderListPage, /visibleOrderItems/)
assert.match(orderListPage, /remainingOrderItemCount/)
assert.match(orderListPage, /order-product-meta/)
assert.match(orderListPage, /redeemSummaryText/)
assert.match(orderListPage, /hydrateMissingOrderItems/)
assert.match(orderListPage, /mapOrderListItem/)
assert.match(orderListPage, /getOrderDetail\(order\.id/)
assert.match(orderListPage, /查看详情/)
assert.match(orderListPage, /key:\s*['"]afterSale['"]/)
assert.match(orderListPage, /isAfterSaleOrder/)
assert.match(orderListPage, /refundStatus/)
assert.doesNotMatch(orderListPage, /tab-badge/)
assert.doesNotMatch(orderListPage, /tab\.count/)
assert.doesNotMatch(orderListPage, /updateTabCounts/)
assert.match(orderListPage, /key:\s*['"]completed['"]/)
assert.match(orderListPage, /completed:\s*3/)
assert.doesNotMatch(orderListPage, /class="therapy-qr-image"/)

assert.match(prescriptionDetailPage, /resolvePrescriptionDoctorName/)
assert.match(prescriptionDetailPage, /resolvePrescriptionDate/)
assert.match(prescriptionDetailPage, /isValidPrescriptionId/)
assert.match(prescriptionDetailPage, /loadOrderFromOrderId/)
assert.match(prescriptionDetailPage, /pageOptions\.orderId/)
assert.match(prescriptionDetailPage, /getOrderDetail/)
assert.match(prescriptionDetailPage, /doctor_name/)
assert.match(prescriptionDetailPage, /createTime/)
assert.match(prescriptionDetailPage, /formatNullableDate/)
assert.doesNotMatch(prescriptionDetailPage, /console\.log\(['"]111111111111111111['"]\)/)
assert.doesNotMatch(prescriptionDetailPage, /\{\{\s*formatDate\(detail\.date\)\s*\}\}/)
